name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Install pygbag
        run: python3 -m pip install pygbag

      - name: Build with pygbag
        run: python3 -m pygbag mordor-rain-web/app --build

      - name: Copy build output to publish folder
        run: |
          mkdir -p public-web
          cp -r mordor-rain-web/app/build/web/* public-web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public-web
          publish_branch: gh-pages