name: Codespace HTTP Preview

on: [push]

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start HTTP server
        run: python -m http.server 8000
