name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Install pygbag
        run: python3 -m pip install pygbag

      - name: Clean previous builds
        run: rm -rf app/build/web

      - name: Build with pygbag
        run: python3 -m pygbag --build --package mordor-rain-web --title "Mordor Rain" app/

      - name: Confirm pygbag output path
        run: |
          find . -type d -name web

      - name: List app/build/web folder contents
        run: ls -l app/build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build/web
          publish_branch: gh-pages