name: Codespace HTTP Preview

on: [push]

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start HTTP server
        run: |
          cd app/build/web 
          python -m http.server 8000 &

      - name: Wait for server to be ready-debug
        uses: harryvasanth/wait-for-http-endpoint@v1
        with:
          url: http://localhost:8000
          method: GET
          expected-status: 200
          timeout: 60000
          interval: 1000

